version: '3.8'

services:
  postgres:
    image: postgres:18.1
    container_name: postgres_db
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data_custom
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data_custom
    restart: unless-stopped
